image: python:3.6

stages:
        - lint
        - test

lint job:
        stage: lint
        before_script:
                - pip install -q -r requirements.txt
                - pip install -q pylint
        script:
                - pylint --exit-zero --output-format=colorized --max-line-length=120 --ignored-modules=matplotlib.cm phs/
                - pylint --exit-zero --output-format=colorized --max-line-length=120 --ignored-modules=matplotlib.cm examples/
                - pylint --exit-zero --output-format=colorized --max-line-length=120 --ignored-modules=matplotlib.cm tests/

integration test parameter definition:
        stage: test
        before_script:
                - pip install -q pytest
                - pip install -q pytest-cov
                - pip install -q -r requirements.txt
                - ./install.sh
        script:
                - pytest --disable-pytest-warnings --cov=phs tests/
