image: python:3.6

stages:
        - lint
        - test

lint job:
        stage: lint
        before_script:
                - pip install -q pylint
        script:
                - pylint phs/
                - pylint examples/
                - pylint tests/

integration test parameter definition:
        stage: lint
        before_script:
                - pip install -q pytest
                - pip install -q pytest-cov
                - pip install -q -r requirements.txt
                - ./install.sh
        script:
                - pytest --disable-pytest-warnings --cov=phs --cov-branch tests/
