image: python:3.6

before_script:
        - sudo apt-get update -qq
        - pip install -r requirements.txt

stages:
        - lint
        - test

lint job:
        stage: lint
        before_script:
                - sudo apt-get install pylint
        script:
                - pylint /phs/parameter_definition.py
