image: python:3.6

before_script:
        - apt-get update -qq
        - pip install -r requirements.txt

stages:
        - lint
        - test

lint job:
        stage: lint
        before_script:
                - pip install pylint
        script:
                - ls
                - pwd
