image: python:3.6

before_script:
        - echo "hello from global before script"

stages:
        - lint
        - test

lint job:
        stage: lint
        before_script:
                - echo "hello from local (lint job) before script"
        script:
                - echo "hello from local (lint job) script"
